micronaut:
  server:
    cors:
      enabled: true
  application:
    name: yira
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5500/postgres
    driverClassName: org.postgresql.Driver
    username: yira
    password: 'yira'
    schema-generate: CREATE_DROP
    dialect: postgres
jpa.default.properties.hibernate.hbm2ddl.auto: update

hello:
  value:
    en: "Hello world from property"
    es: "Hola mundo desde la propiedad"